name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name : libs1
      run : sudo apt-get install libsdl-image1.2 libsdl-image1.2-dev libsdl1.2-dev libsdl1.2debian
    - name : libs2
      run : sudo apt-get install v4l-utils
    - name : make
      run : cd src && make
    - name: make verif_line
      run: cd src && make verif_line
    - name : space verification
      run : cd src && make verif_space
